AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  githubpassword:
    Type: String
Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                - 'codebuild:*'
                Effect: Allow
                Resource: '*'
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "CodeBuildNestedCFNAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:Get*"
                  - "cloudformation:Describe*"
                  - "cloudformation:List*"
                Resource:
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Wordpress-${AWS::StackName}*
              -
                Effect: "Allow"
                Action:
                  - "codecommit:ListBranches"
                  - "codecommit:ListRepositories"
                  - "codecommit:BatchGetRepositories"
                  - "codecommit:Get*"
                  - "codecommit:GitPull"
                Resource:
                  - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:wordpress-build-test
              -
                Effect: "Allow"
                Action:
                  - "ec2:Describe*"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "cloudformation:ValidateTemplate"
                  - "elasticloadbalancing:Describe*"
                  - "autoscaling:Describe*"
                  - "iam:Get*"
                  - "iam:List*"
                  - "logs:Describe*"
                  - "logs:Get*"
                  - "route53:ListResourceRecordSets"
                  - "tag:Get*"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn:aws:s3:::codepipeline-${AWS::Region}-*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreBucket}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreBucket}/*
  MicroqoderCBProjectLabel:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MicroqoderCBProject
      Description: Build Grails inside Docker
      ServiceRole:
        Fn::GetAtt: [ CodeBuildRole, Arn ]
      Artifacts:
        Type: S3
        Location: !Ref ArtifactStoreBucket
        Name: CodeDeployArtifactDummy
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: craigwongva/grails240:grails240
      Source:
        Location: https://github.com/craigwongva/microqoder
        BuildSpec: buildspec.yml
        Type: GITHUB
        Auth: 
          Type: OAUTH
      TimeoutInMinutes: 5
  MicroqoderCDServiceRoleLabel:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MicroqoderCodeDeployServiceRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
#  CD4InstanceRole:
#    Type: AWS::IAM::Role
#    Properties:
#      ManagedPolicyArns:
#      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#        - Effect: Allow
#          Principal:
#            Service:
#            - ec2.amazonaws.com
#          Action:
#          - sts:AssumeRole
#      Path: "/"
  TomcatEC2InstanceProfileDummy:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - CD2InstanceRole
      InstanceProfileName: TomcatEC2InstanceProfileName
  TomcatEC2InstanceSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-a0383dc5
      GroupDescription: dummy01
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 173.242.16.106/32
        FromPort: 8080
        IpProtocol: tcp
        ToPort: 8080
  TomcatEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: TomcatEC2InstanceProfileName
      KeyName: oregonkeypair
      SecurityGroupIds: 
        - !Ref TomcatEC2InstanceSecGrp
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"
              - "aws s3 cp 's3://aws-codedeploy-us-east-1/latest/codedeploy-agent.noarch.rpm' . --region us-east-1\n"
              - "yum -y install codedeploy-agent.noarch.rpm\n"              
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://github.com/craigwongva/microqoder'\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/microqoder; ./userdata-install-awslogs'\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/microqoder; ./userdata-install-tomcat' \n"
      InstanceType: t2.micro
      ImageId: ami-32d8124a
      Tags:
        - Key: Name
          Value: MicroqoderTomcatEC2Instance

  MicroqoderCDAppLabel:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: MicroqoderCDApp
  MicroqoderCDGroupDummy:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: MicroqoderCDServiceRoleLabel
    DependsOn: MicroqoderCDAppLabel    
    Properties:
      ApplicationName: MicroqoderCDApp
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: MicroqoderCDGroup
      Ec2TagFilters:
        - Key: Name
          Value: MicroqoderTomcatEC2Instance
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt [MicroqoderCDServiceRoleLabel, Arn]      
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      DisableInboundStageTransitions: []
      Name: MicroqoderPipeline
#replaced 3/6 8:40am
#      RoleArn: !GetAtt [PipelineRole, Arn]
      RoleArn: "arn:aws:iam::994238729631:role/AWS-CodePipeline-Service"
      Stages:
        - Name: Sourcing
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: craigwongva
                Repo: microqoder
                Branch: master
                OAuthToken: !Ref githubpassword
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceArtifact 
              RunOrder: 2              
        - Name: BuildStage
          Actions:
            - Name: BuildAction
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: MicroqoderCBProject
              OutputArtifacts:                
                - Name: BuildArtifact                 
              RunOrder: 5
        - Name: DeployStage
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1            
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ApplicationName: MicroqoderCDApp
                DeploymentGroupName: MicroqoderCDGroup
Outputs:
  artifactStoreBucketOutput:
    Value: !Ref ArtifactStoreBucket
    Export:
      Name: wordpress-build-test-artifact-store-bucket